### ISSUE TITLE
Code style: Mandate unqualified types in the absence of conflict and explicit import statements

### ISSUE THREAD

**Issue by Kleidukos** [haskellfoundation/HaskellSchool#8]
I do not wish to clutter the reading with qualified data-types for APIs whose functions have conflicts (Vector, Text, Map, Set, etc).

We should do this instead:

```
import Data.Vector (Vector)
import qualified Data.Vector as V
```

**Comment by TrueBoxGuy** [comment]
Do you want me to integrate this into the style guide as part of resolving the issue? 

I can also check that pull requests conform to this.

**Comment by Kleidukos** [comment]
@TrueBoxGuy Yes that was for introduction in the style guide. :)
